master:
  hosts:
    192.168.30.52:
node:
  hosts:
    192.168.30.53:
all:
  children:
    master:
    node:
  vars:
    repolist:
      - { src: "kubernetes.repo", dest: "/etc/yum.repos.d/kubernetes.repo" }
      - { src: "docker-ce.repo", dest: "/etc/yum.repos.d/docker-ce.repo" }
    k8sver: 1.18.2
    etc_hosts:
      - "192.168.30.52 k8s1"
      - "192.168.30.53 k8s2"
    imghub: registry.aliyuncs.com/google_containers
    podcidr: 172.10.0.0/16