- name: 安装keepalived和ipvsadm
  yum:
    name: "{{ item }}"
  with_items:
    - "keepalived"
    - "ipvsadm"

- name: 替换配置文件
  template:
    src: "keepalived.conf.j2"
    dest: /etc/keepalived/keepalived.conf

- name: 创建目录
  file: 
    path: "/etc/keepalived/{{ item }}"
    state: directory
  with_items:
    - "vip"
    - "conf"

- name: 创建空的文件以致不会让keepalived报错
  file:
    path: "{{ item }}"
    state: touch
  with_items:
    - "/etc/keepalived/vip/default.vip"
    - "/etc/keepalived/conf/default.vs"

- name: 启动进程和加到开机启动
  service:
    name: keepalived
    state: started
    enabled: yes
