---
- name: 拷贝vip文件
  template:
    src: sample.vip.j2
    dest: "/etc/keepalived/vip/{{ item.vip }}.vip"
  with_items:
    - "{{ requestlist }}"

- name: copy vs文件
  template:
    src: sample.vs.j2
    dest: "/etc/keepalived/conf/{{ item.vip }}_{{ item.vport }}_{{ item.prot|replace('https','tcp')|replace('http','tcp')|upper }}.vs"
  with_items:
    - "{{ requestlist }}"

- name: 创建rs文件的目录
  file:
    path: "/etc/keepalived/conf/{{ item.vip }}_{{ item.vport }}_{{ item.prot|replace('https','tcp')|replace('http','tcp')|upper }}"
    state: directory
  with_items:
    - "{{ requestlist }}"

- name: 拷贝rs文件
  template:
    src: sample.rs.j2
    dest: "/etc/keepalived/conf/{{ item[1].vip }}_{{ item[1].vport }}_{{ item[1].prot|replace('https','tcp')|replace('http','tcp')|upper }}/{{ item[0] }}_{{ item[1].vport }}.rs"
  with_nested:
    - "{{ groups['nginx'] }}"
    - "{{ requestlist }}"

- name: 重启keepalived服务
  service:
    name: keepalived
    state: restarted