---
- name: 创建证书目录
  file:
    path: "/etc/nginx/conf.d/ssl"
    state: directory
  when: tlsup == 'yes'

- name: 上传证书
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/conf.d/ssl"
  with_items:
    - "{{ tlslist }}"
  
- name: 拷贝nginx的vip配置文件
  template:
    src: "nginx_sample.j2"
    dest: "/etc/nginx/conf.d/{{ item.vip }}_{{ item.vport }}_{{ item.prot }}.{{ item.prot|replace('tcp','stream')|replace('udp','stream')|replace('https','conf')|replace('http','conf') }}"
  with_items:
    - "{{ requestlist }}"

- name: 添加vip本地回路
  shell: |
    if ip a s lo|grep global|grep -wq {{ item.vip }}/32;then
      ip addr del {{ item.vip }}/32 dev lo && ip addr add {{ item.vip }}/32 dev lo
    else
      ip addr add {{ item.vip }}/32 dev lo
    fi
  with_items:
    - "{{ requestlist }}"

- name: 添加本地回路开机启动
  lineinfile:
    path: /etc/rc.d/rc.local
    line: "ip addr add {{ item.vip }}/32 dev lo"
    mode: 0755
  with_items:
    - "{{ requestlist }}"

- name: 语法检查和重载服务
  shell: |
    nginx -t && nginx -s reload